### PR TITLE
67 patient

### LINKED ISSUE #69: Create util function to strip the text to display the text only without numbering
We will need to use this function a lot in all kinds of component for display purpose. It is best to have a function in util file so there is no need to create new function every time when we need to strip the text. For now this function is called valueOnly and it is in file objectutil.js

### PR DESCRIPTION
**Pull request by mingjiecn**
close #69 #68 #67 

image

image

### CODE REVIEW

**Review by vsmalladi — APPROVED** [review]
Code looks great. Should discuss implications on Tuesday with redcap2json and further building of schemas with @SenseCode

**Comment by mingjiecn** [comment]
New look for forms table:
image

**Review by vsmalladi — APPROVED** [review]
Looks good. Works for me.

Ill wait for @SenseCode to also test.

**Review by SenseCode — APPROVED** [review]
Pretty good now can show all the forms just in 5 packets  and save a lot space.
One more thing we need to unify form name ， like ivp_a1 or A1-ivp in the future, so I can change in the schema. Very small error, should use uppercase in facets. Great job!
image

**Pull request merged**
