### PR TITLE
144 ubuntu upgrade

### LINKED ISSUE #144: Ubuntu 18 upgrade

### PR DESCRIPTION
**Pull request by vsmalladi**
Close #144 

Upgrading to Ubuntu18

### CODE REVIEW

**Comment by vsmalladi** [comment]
@mingjiecn @SenseCode Fixed load issues Give it another test.

**Comment by SenseCode** [comment]
image
image

**Comment by SenseCode** [comment]
Can run server locally, when input patient in searchbox,it shows error as below:
image
image
then the server dead. I cannot open any of the schema input forms so far.

**Review by mingjiecn — CHANGES_REQUESTED** [review]
Have the same error that @SenseCode had. Looks like there are some issues in file search.js.

**Review by mingjiecn — APPROVED** [review]
Patient search page, patient report page and patient view page is working now

**Review by SenseCode — APPROVED** [review]
Give authorization before merging with ce_meger_fix branch

**Pull request merged**
